### ISSUE TITLE
Errors with the access rights.

### ISSUE THREAD

**Issue by ipod86** [linuxserver/docker-projectsend#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, 

I have just installed projectsend with docker compose. Unfortunately there are errors with the access rights. What could this be?
```
version: "2.1"
services:
  projectsend:
    image: linuxserver/projectsend:latest
    container_name: projectsend
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Berlin
      - MAX_UPLOAD=5000
    volumes:
      - ./config:/config 
      - ./data:/data
    ports:
      - 88:80
    restart: unless-stopped
  db:
    image: mariadb:latest
    container_name: mariadb-projectsend
    environment:
      MYSQL_ROOT_PASSWORD: projectsend
      MYSQL_DATABASE: projectsend
      MYSQL_USER: projectsend
      MYSQL_PASSWORD: projectsend
    volumes:
      - ./sql:/var/lib/mysql 

    restart: unless-stopped
```
![Screenshot_20240824_114157_Chrome](https://github.com/user-attachments/assets/036378bc-6101-49d0-b77c-774050619233)

### Expected Behavior

Run my docker compose

### Steps To Reproduce

Run my docker compose

### Environment

```markdown
Debian 12
Compose with Portainer
```

### CPU architecture

x86-64

### Docker creation

```bash
My docker compose in Portainer
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    998
User GID:    100
───────────────────────────────────────
Linuxserver.io version: r1720-ls204
Build-date: 2024-08-19T21:29:51+00:00
───────────────────────────────────────
    
using keys found in /config/keys
New container detected. Setting up app folder and fixing permissions.
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```
