### ISSUE TITLE
[BUG] Database configuration not working after setup project send 

### ISSUE THREAD

**Issue by UbuntuEvangelist** [linuxserver/docker-projectsend#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Database configuration

![Screenshot from 2024-11-07 04-20-04](https://github.com/user-attachments/assets/22f5e086-9a99-4495-8618-c148e50b58e5)

### Expected Behavior

database configuration not working after setup project send

### Steps To Reproduce

added mysql db, usr and password on docker-compose.yml file
restart all docker images

### Environment

```markdown
- OS: Ubuntu 24.04.1 LTS
- How docker service was installed:
Docker version 27.3.1, build ce12230
```

### CPU architecture

x86-64

### Docker creation

```bash
docker pull linuxserver/projectsend
docker run -d \
  --name=projectsend \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -e MAX_UPLOAD=5000 \
  -p 80:80 \
  -v /path/to/projectsend/config:/config \
  -v /path/to/data:/data \
  --restart unless-stopped \
  lscr.io/linuxserver/projectsend:latest
```

### Container logs

```bash
██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: r1720-ls212
Build-date: 2024-10-28T21:26:37+00:00
───────────────────────────────────────
    
using keys found in /config/keys
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by johanbluecreek** [comment]
I have the same issue as this and cannot find a resolution in the docs. I think this should be reopened.

**Comment by goNeuland** [comment]
Hello,
You simply need to add a database to the Docker Compose file. You can then connect to this.

It works for me.

Best regards

**Comment by Nov1kov** [comment]
Has anyone a full example of docker-compose with database?

**Comment by Nov1kov** [comment]
Yes:

1. Add the db service in your docker compose
```
 mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/London
    volumes:
      - /project_send/mariadb:/config
    ports:
      - 127.0.0.1:3306:3306
    restart: unless-stopped
```

2. Up service:
```
docker compose up -d mariadb
```

3. Create db:
```
docker exec -it mariadb bash
mysql -u root -proot
CREATE DATABASE projectsend;
```

4. setup the config file in web ui.
- db host: mariadb:3306
other config keep defaults.
